# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  port: 5432
  pool: 5
  username: <%= ENV['GEOBLACKLIGHT_DATABASE_USER'] %>
  password: <%= ENV['GEOBLACKLIGHT_DATABASE_PASSWORD'] %>
  database: geoblacklight

test:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3

development:
  <<: *default

production:
  <<: *default